import type { Config } from "tailwindcss";

const mantineFontFamily = {
  mantine: [
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica",
    "Arial",
    "sans-serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
  ],
  "mantine-monospace": [
    "ui-monospace",
    "SFMono-Regular",
    "Menlo",
    "Monaco",
    "Consolas",
    "Liberation Mono",
    "Courier New",
    "monospace",
  ],
  "mantine-headings": [
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica",
    "Arial",
    "sans-serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
  ],
};

const mantineFontSize = {
  "mantine-xs": "0.75rem",
  "mantine-sm": "0.875rem",
  "mantine-md": "1rem",
  "mantine-lg": "1.125rem",
  "mantine-xl": "1.25rem",
  "mantine-h1": "2.125rem",
  "mantine-h2": "1.625rem",
  "mantine-h3": "1.375rem",
  "mantine-h4": "1.125rem",
  "mantine-h5": "1rem",
  "mantine-h6": "0.875rem",
};

const mantineLineHeight = {
  "mantine-xs": "1.4",
  "mantine-sm": "1.45",
  "mantine-md": "1.55",
  "mantine-lg": "1.6",
  "mantine-xl": "1.65",
  "mantine-h1": "1.3",
  "mantine-h2": "1.35",
  "mantine-h3": "1.4",
  "mantine-h4": "1.45",
  "mantine-h5": "1.5",
  "mantine-h6": "1.5",
};

const mantineSpacing = {
  "mantine-xs": "0.625rem",
  "mantine-sm": "0.75rem",
  "mantine-md": "1rem",
  "mantine-lg": "1.25rem",
  "mantine-xl": "2rem",
};

const mantineBorderRadius = {
  "mantine-xs": "0.125rem",
  "mantine-sm": "0.25rem",
  "mantine-md": "0.5rem",
  "mantine-lg": "1rem",
  "mantine-xl": "2rem",
  "mantine-default": "0.25rem",
};

const mantineBoxShadow = {
  "mantine-xs":
    "0 0.0625rem 0.1875rem rgba(0, 0, 0, 0.05), 0 0.0625rem 0.125rem rgba(0, 0, 0, 0.1)",
  "mantine-sm":
    "0 0.0625rem 0.1875rem rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 0.625rem 0.9375rem -0.3125rem, rgba(0, 0, 0, 0.04) 0 0.4375rem 0.4375rem -0.3125rem",
  "mantine-md":
    "0 0.0625rem 0.1875rem rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 1.25rem 1.5625rem -0.3125rem, rgba(0, 0, 0, 0.04) 0 0.625rem 0.625rem -0.3125rem",
  "mantine-lg":
    "0 0.0625rem 0.1875rem rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 1.75rem 1.4375rem -0.4375rem, rgba(0, 0, 0, 0.04) 0 0.75rem 0.75rem -0.4375rem",
  "mantine-xl":
    "0 0.0625rem 0.1875rem rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 2.25rem 1.75rem -0.4375rem, rgba(0, 0, 0, 0.04) 0 1.0625rem 1.0625rem -0.4375rem",
};

const mantineColors = {
  mantineColorWhite: "#fff",
  mantineColorBlack: "#000",
  mantineColorDark0: "#C9C9C9",
  mantineColorDark1: "#b8b8b8",
  mantineColorDark2: "#828282",
  mantineColorDark3: "#696969",
  mantineColorDark4: "#424242",
  mantineColorDark5: "#3b3b3b",
  mantineColorDark6: "#2e2e2e",
  mantineColorDark7: "#242424",
  mantineColorDark8: "#1f1f1f",
  mantineColorDark9: "#141414",
  mantineColorGray0: "#f8f9fa",
  mantineColorGray1: "#f1f3f5",
  mantineColorGray2: "#e9ecef",
  mantineColorGray3: "#dee2e6",
  mantineColorGray4: "#ced4da",
  mantineColorGray5: "#adb5bd",
  mantineColorGray6: "#868e96",
  mantineColorGray7: "#495057",
  mantineColorGray8: "#343a40",
  mantineColorGray9: "#212529",
  mantineColorRed0: "#fff5f5",
  mantineColorRed1: "#ffe3e3",
  mantineColorRed2: "#ffc9c9",
  mantineColorRed3: "#ffa8a8",
  mantineColorRed4: "#ff8787",
  mantineColorRed5: "#ff6b6b",
  mantineColorRed6: "#fa5252",
  mantineColorRed7: "#f03e3e",
  mantineColorRed8: "#e03131",
  mantineColorRed9: "#c92a2a",
  mantineColorPink0: "#fff0f6",
  mantineColorPink1: "#ffdeeb",
  mantineColorPink2: "#fcc2d7",
  mantineColorPink3: "#faa2c1",
  mantineColorPink4: "#f783ac",
  mantineColorPink5: "#f06595",
  mantineColorPink6: "#e64980",
  mantineColorPink7: "#d6336c",
  mantineColorPink8: "#c2255c",
  mantineColorPink9: "#a61e4d",
  mantineColorGrape0: "#f8f0fc",
  mantineColorGrape1: "#f3d9fa",
  mantineColorGrape2: "#eebefa",
  mantineColorGrape3: "#e599f7",
  mantineColorGrape4: "#da77f2",
  mantineColorGrape5: "#cc5de8",
  mantineColorGrape6: "#be4bdb",
  mantineColorGrape7: "#ae3ec9",
  mantineColorGrape8: "#9c36b5",
  mantineColorGrape9: "#862e9c",
  mantineColorViolet0: "#f3f0ff",
  mantineColorViolet1: "#e5dbff",
  mantineColorViolet2: "#d0bfff",
  mantineColorViolet3: "#b197fc",
  mantineColorViolet4: "#9775fa",
  mantineColorViolet5: "#845ef7",
  mantineColorViolet6: "#7950f2",
  mantineColorViolet7: "#7048e8",
  mantineColorViolet8: "#6741d9",
  mantineColorViolet9: "#5f3dc4",
  mantineColorIndigo0: "#edf2ff",
  mantineColorIndigo1: "#dbe4ff",
  mantineColorIndigo2: "#bac8ff",
  mantineColorIndigo3: "#91a7ff",
  mantineColorIndigo4: "#748ffc",
  mantineColorIndigo5: "#5c7cfa",
  mantineColorIndigo6: "#4c6ef5",
  mantineColorIndigo7: "#4263eb",
  mantineColorIndigo8: "#3b5bdb",
  mantineColorIndigo9: "#364fc7",
  mantineColorBlue0: "#e7f5ff",
  mantineColorBlue1: "#d0ebff",
  mantineColorBlue2: "#a5d8ff",
  mantineColorBlue3: "#74c0fc",
  mantineColorBlue4: "#4dabf7",
  mantineColorBlue5: "#339af0",
  mantineColorBlue6: "#228be6",
  mantineColorBlue7: "#1c7ed6",
  mantineColorBlue8: "#1971c2",
  mantineColorBlue9: "#1864ab",
  mantineColorCyan0: "#e3fafc",
  mantineColorCyan1: "#c5f6fa",
  mantineColorCyan2: "#99e9f2",
  mantineColorCyan3: "#66d9e8",
  mantineColorCyan4: "#3bc9db",
  mantineColorCyan5: "#22b8cf",
  mantineColorCyan6: "#15aabf",
  mantineColorCyan7: "#1098ad",
  mantineColorCyan8: "#0c8599",
  mantineColorCyan9: "#0b7285",
  mantineColorTeal0: "#e6fcf5",
  mantineColorTeal1: "#c3fae8",
  mantineColorTeal2: "#96f2d7",
  mantineColorTeal3: "#63e6be",
  mantineColorTeal4: "#38d9a9",
  mantineColorTeal5: "#20c997",
  mantineColorTeal6: "#12b886",
  mantineColorTeal7: "#0ca678",
  mantineColorTeal8: "#099268",
  mantineColorTeal9: "#087f5b",
  mantineColorGreen0: "#ebfbee",
  mantineColorGreen1: "#d3f9d8",
  mantineColorGreen2: "#b2f2bb",
  mantineColorGreen3: "#8ce99a",
  mantineColorGreen4: "#69db7c",
  mantineColorGreen5: "#51cf66",
  mantineColorGreen6: "#40c057",
  mantineColorGreen7: "#37b24d",
  mantineColorGreen8: "#2f9e44",
  mantineColorGreen9: "#2b8a3e",
  mantineColorLime0: "#f4fce3",
  mantineColorLime1: "#e9fac8",
  mantineColorLime2: "#d8f5a2",
  mantineColorLime3: "#c0eb75",
  mantineColorLime4: "#a9e34b",
  mantineColorLime5: "#94d82d",
  mantineColorLime6: "#82c91e",
  mantineColorLime7: "#74b816",
  mantineColorLime8: "#66a80f",
  mantineColorLime9: "#5c940d",
  mantineColorYellow0: "#fff9db",
  mantineColorYellow1: "#fff3bf",
  mantineColorYellow2: "#ffec99",
  mantineColorYellow3: "#ffe066",
  mantineColorYellow4: "#ffd43b",
  mantineColorYellow5: "#fcc419",
  mantineColorYellow6: "#fab005",
  mantineColorYellow7: "#f59f00",
  mantineColorYellow8: "#f08c00",
  mantineColorYellow9: "#e67700",
  mantineColorOrange0: "#fff4e6",
  mantineColorOrange1: "#ffe8cc",
  mantineColorOrange2: "#ffd8a8",
  mantineColorOrange3: "#ffc078",
  mantineColorOrange4: "#ffa94d",
  mantineColorOrange5: "#ff922b",
  mantineColorOrange6: "#fd7e14",
  mantineColorOrange7: "#f76707",
  mantineColorOrange8: "#e8590c",
  mantineColorOrange9: "#d9480f",
};

const mantinePrimaryColors = {
  mantinePrimaryColor0: mantineColors.mantineColorBlue0,
  mantinePrimaryColor1: mantineColors.mantineColorBlue1,
  mantinePrimaryColor2: mantineColors.mantineColorBlue2,
  mantinePrimaryColor3: mantineColors.mantineColorBlue3,
  mantinePrimaryColor4: mantineColors.mantineColorBlue4,
  mantinePrimaryColor5: mantineColors.mantineColorBlue5,
  mantinePrimaryColor6: mantineColors.mantineColorBlue6,
  mantinePrimaryColor7: mantineColors.mantineColorBlue7,
  mantinePrimaryColor8: mantineColors.mantineColorBlue8,
  mantinePrimaryColor9: mantineColors.mantineColorBlue9,
};

const mantineLightColor = {
  mantineColorDarkFilled: mantineColors.mantineColorDark6,
  mantineColorGrayFilled: mantineColors.mantineColorGray6,
  mantineColorRedFilled: mantineColors.mantineColorRed6,
  mantineColorPinkFilled: mantineColors.mantineColorPink6,
  mantineColorGrapeFilled: mantineColors.mantineColorGrape6,
  mantineColorVioletFilled: mantineColors.mantineColorViolet8,
  mantineColorVioletOutline: mantineColors.mantineColorViolet6,
};

const mantineLightColorScheme = {
  mantineLightPrimaryColorContrast: mantineColors.mantineColorWhite,
  mantineLightColorBright: mantineColors.mantineColorBlack,
  mantineLightColorText: "#000",
  mantineLightColorBody: "#fff",
  mantineLightColorError: mantineColors.mantineColorRed6,
  mantineLightColorPlaceholder: mantineColors.mantineColorGray5,
  mantineLightColorAnchor: mantineColors.mantineColorBlue6,
  mantineLightColorDefault: mantineColors.mantineColorWhite,
  mantineLightColorDefaultHover: mantineColors.mantineColorGray0,
  mantineLightColorDefaultColor: mantineColors.mantineColorBlack,
  mantineLightColorDefaultBorder: mantineColors.mantineColorGray4,
  mantineLightColorDimmed: mantineColors.mantineColorGray6,
  mantineLightColorDarkText: mantineLightColor.mantineColorDarkFilled,
  mantineLightColorDarkFilled: mantineColors.mantineColorDark6,
  mantineLightColorDarkFilledHover: mantineColors.mantineColorDark7,
  mantineLightColorDarkLight: "rgba(46, 46, 46, 0.1)",
  mantineLightColorDarkLightHover: "rgba(46, 46, 46, 0.12)",
  mantineLightColorDarkLightColor: mantineColors.mantineColorDark6,
  mantineLightColorDarkOutline: mantineColors.mantineColorDark6,
  mantineLightColorDarkOutlineHover: "rgba(46, 46, 46, 0.05)",
  mantineLightColorGrayText: mantineLightColor.mantineColorGrayFilled,
  mantineLightColorGrayFilled: mantineColors.mantineColorGray6,
  mantineLightColorGrayFilledHover: mantineColors.mantineColorGray7,
  mantineLightColorGrayLight: "rgba(134, 142, 150, 0.1)",
  mantineLightColorGrayLightHover: "rgba(134, 142, 150, 0.12)",
  mantineLightColorGrayLightColor: mantineColors.mantineColorGray6,
  mantineLightColorGrayOutline: mantineColors.mantineColorGray6,
  mantineLightColorGrayOutlineHover: "rgba(134, 142, 150, 0.05)",
  mantineLightColorRedText: mantineLightColor.mantineColorRedFilled,
  mantineLightColorRedFilled: mantineColors.mantineColorRed6,
  mantineLightColorRedFilledHover: mantineColors.mantineColorRed7,
  mantineLightColorRedLight: "rgba(250, 82, 82, 0.1)",
  mantineLightColorRedLightHover: "rgba(250, 82, 82, 0.12)",
  mantineLightColorRedLightColor: mantineColors.mantineColorRed6,
  mantineLightColorRedOutline: mantineColors.mantineColorRed6,
  mantineLightColorRedOutlineHover: "rgba(250, 82, 82, 0.05)",
  mantineLightColorPinkText: mantineLightColor.mantineColorPinkFilled,
  mantineLightColorPinkFilled: mantineColors.mantineColorPink6,
  mantineLightColorPinkFilledHover: mantineColors.mantineColorPink7,
  mantineLightColorPinkLight: "rgba(230, 73, 128, 0.1)",
  mantineLightColorPinkLightHover: "rgba(230, 73, 128, 0.12)",
  mantineLightColorPinkLightColor: mantineColors.mantineColorPink6,
  mantineLightColorPinkOutline: mantineColors.mantineColorPink6,
  mantineLightColorPinkOutlineHover: "rgba(230, 73, 128, 0.05)",
  mantineLightColorGrapeText: mantineLightColor.mantineColorGrapeFilled,
  mantineLightColorGrapeFilled: mantineColors.mantineColorGrape6,
  mantineLightColorGrapeFilledHover: mantineColors.mantineColorGrape7,
  mantineLightColorGrapeLight: "rgba(190, 75, 219, 0.1)",
  mantineLightColorGrapeLightHover: "rgba(190, 75, 219, 0.12)",
  mantineLightColorGrapeLightColor: mantineColors.mantineColorGrape6,
  mantineLightColorGrapeOutline: mantineColors.mantineColorGrape6,
  mantineLightColorGrapeOutlineHover: "rgba(190, 75, 219, 0.05)",
  mantineLightColorVioletText: mantineLightColor.mantineColorVioletFilled,
  mantineLightColorVioletFilled: mantineColors.mantineColorViolet6,
  mantineLightColorVioletFilledHover: mantineColors.mantineColorViolet7,
  mantineLightColorVioletLight: "rgba(121, 80, 242, 0.1)",
  mantineLightColorVioletLightHover: "rgba(121, 80, 242, 0.12)",
  mantineLightColorVioletLightColor: mantineColors.mantineColorViolet6,
  mantineLightColorVioletOutline: mantineLightColor.mantineColorVioletOutline,
};

// const mantineDarkColor = {
//   mantineColorDarkFilled: mantineColors.mantineColorDark8,
//   mantineColorGrayFilled: mantineColors.mantineColorGray8,
//   mantineColorRedFilled: mantineColors.mantineColorRed8,
//   mantineColorPinkFilled: mantineColors.mantineColorPink8,
//   mantineColorGrapeFilled: mantineColors.mantineColorGrape8,
//   mantineColorVioletFilled: mantineColors.mantineColorViolet8,
//   mantineColorVioletOutline: mantineColors.mantineColorViolet4,
// };

const mantineDarkColorScheme = {
  mantineDarkPrimaryColorContrast: mantineColors.mantineColorWhite,
  mantineDarkColorBright: mantineColors.mantineColorWhite,
  mantineDarkColorText: mantineColors.mantineColorDark0,
  mantineDarkColorBody: mantineColors.mantineColorDark7,
  mantineDarkColorError: mantineColors.mantineColorRed8,
  mantineDarkColorPlaceholder: mantineColors.mantineColorDark3,
  mantineDarkColorAnchor: mantineColors.mantineColorBlue4,
  mantineDarkColorDefault: mantineColors.mantineColorDark6,
  mantineDarkColorDefaultHover: mantineColors.mantineColorDark5,
  mantineDarkColorDefaultColor: mantineColors.mantineColorWhite,
  mantineDarkColorDefaultBorder: mantineColors.mantineColorDark4,
  mantineDarkColorDimmed: mantineColors.mantineColorDark2,
  mantineDarkColorDarkText: mantineColors.mantineColorDark4,
  mantineDarkColorDarkFilled: mantineColors.mantineColorDark8,
  mantineDarkColorDarkFilledHover: mantineColors.mantineColorDark9,
  mantineDarkColorDarkLight: "rgba(46, 46, 46, 0.15)",
  mantineDarkColorDarkLightHover: "rgba(46, 46, 46, 0.2)",
  mantineDarkColorDarkLightColor: mantineColors.mantineColorDark3,
  mantineDarkColorDarkOutline: mantineColors.mantineColorDark4,
  mantineDarkColorDarkOutlineHover: "rgba(66, 66, 66, 0.05)",
  mantineDarkColorGrayText: mantineColors.mantineColorGray4,
  mantineDarkColorGrayFilled: mantineColors.mantineColorGray8,
  mantineDarkColorGrayFilledHover: mantineColors.mantineColorGray9,
  mantineDarkColorGrayLight: "rgba(134, 142, 150, 0.15)",
  mantineDarkColorGrayLightHover: "rgba(134, 142, 150, 0.2)",
  mantineDarkColorGrayLightColor: mantineColors.mantineColorGray3,
  mantineDarkColorGrayOutline: mantineColors.mantineColorGray4,
  mantineDarkColorGrayOutlineHover: "rgba(206, 212, 218, 0.05)",
  mantineDarkColorRedText: mantineColors.mantineColorRed4,
  mantineDarkColorRedFilled: mantineColors.mantineColorRed8,
  mantineDarkColorRedFilledHover: mantineColors.mantineColorRed9,
  mantineDarkColorRedLight: "rgba(250, 82, 82, 0.15)",
  mantineDarkColorRedLightHover: "rgba(250, 82, 82, 0.2)",
  mantineDarkColorRedLightColor: mantineColors.mantineColorRed3,
  mantineDarkColorRedOutline: mantineColors.mantineColorRed4,
  mantineDarkColorRedOutlineHover: "rgba(255, 135, 135, 0.05)",
  mantineDarkColorPinkText: mantineColors.mantineColorPink4,
  mantineDarkColorPinkFilled: mantineColors.mantineColorPink8,
  mantineDarkColorPinkFilledHover: mantineColors.mantineColorPink9,
  mantineDarkColorPinkLight: "rgba(230, 73, 128, 0.15)",
  mantineDarkColorPinkLightHover: "rgba(230, 73, 128, 0.2)",
  mantineDarkColorPinkLightColor: mantineColors.mantineColorPink3,
  mantineDarkColorPinkOutline: mantineColors.mantineColorPink4,
  mantineDarkColorPinkOutlineHover: "rgba(247, 131, 172, 0.05)",
  mantineDarkColorGrapeText: mantineColors.mantineColorGrape4,
  mantineDarkColorGrapeFilled: mantineColors.mantineColorGrape8,
  mantineDarkColorGrapeFilledHover: mantineColors.mantineColorGrape9,
  mantineDarkColorGrapeLight: "rgba(190, 75, 219, 0.15)",
  mantineDarkColorGrapeLightHover: "rgba(190, 75, 219, 0.2)",
  mantineDarkColorGrapeLightColor: mantineColors.mantineColorGrape3,
  mantineDarkColorGrapeOutline: mantineColors.mantineColorGrape4,
  mantineDarkColorGrapeOutlineHover: "rgba(218, 119, 242, 0.05)",
  mantineDarkColorVioletText: mantineColors.mantineColorViolet4,
  mantineDarkColorVioletFilled: mantineColors.mantineColorViolet8,
  mantineDarkColorVioletFilledHover: mantineColors.mantineColorViolet9,
  mantineDarkColorVioletLight: "rgba(121, 80, 242, 0.15)",
  mantineDarkColorVioletLightHover: "rgba(121, 80, 242, 0.2)",
  mantineDarkColorVioletLightColor: mantineColors.mantineColorViolet3,
  mantineDarkColorVioletOutline: mantineColors.mantineColorViolet4,
  mantineDarkColorVioletOutlineHover: "rgba(151, 117, 250, 0.05)",
  mantineDarkColorIndigoText: mantineColors.mantineColorIndigo4,
  mantineDarkColorIndigoFilled: mantineColors.mantineColorIndigo8,
  mantineDarkColorIndigoFilledHover: mantineColors.mantineColorIndigo9,
  mantineDarkColorIndigoLight: "rgba(76, 110, 245, 0.15)",
  mantineDarkColorIndigoLightHover: "rgba(76, 110, 245, 0.2)",
  mantineDarkColorIndigoLightColor: mantineColors.mantineColorIndigo3,
  mantineDarkColorIndigoOutline: mantineColors.mantineColorIndigo4,
  mantineDarkColorIndigoOutlineHover: "rgba(116, 143, 252, 0.05)",
  mantineDarkColorBlueText: mantineColors.mantineColorBlue4,
  mantineDarkColorBlueFilled: mantineColors.mantineColorBlue8,
  mantineDarkColorBlueFilledHover: mantineColors.mantineColorBlue9,
  mantineDarkColorBlueLight: "rgba(34, 139, 230, 0.15)",
  mantineDarkColorBlueLightHover: "rgba(34, 139, 230, 0.2)",
  mantineDarkColorBlueLightColor: mantineColors.mantineColorBlue3,
  mantineDarkColorBlueOutline: mantineColors.mantineColorBlue4,
  mantineDarkColorBlueOutlineHover: "rgba(77, 171, 247, 0.05)",
  mantineDarkColorCyanText: mantineColors.mantineColorCyan4,
  mantineDarkColorCyanFilled: mantineColors.mantineColorCyan8,
  mantineDarkColorCyanFilledHover: mantineColors.mantineColorCyan9,
  mantineDarkColorCyanLight: "rgba(21, 170, 191, 0.15)",
  mantineDarkColorCyanLightHover: "rgba(21, 170, 191, 0.2)",
  mantineDarkColorCyanLightColor: mantineColors.mantineColorCyan3,
  mantineDarkColorCyanOutline: mantineColors.mantineColorCyan4,
  mantineDarkColorCyanOutlineHover: "rgba(59, 201, 219, 0.05)",
  mantineDarkColorTealText: mantineColors.mantineColorTeal4,
  mantineDarkColorTealFilled: mantineColors.mantineColorTeal8,
  mantineDarkColorTealFilledHover: mantineColors.mantineColorTeal9,
  mantineDarkColorTealLight: "rgba(18, 184, 134, 0.15)",
  mantineDarkColorTealLightHover: "rgba(18, 184, 134, 0.2)",
  mantineDarkColorTealLightColor: mantineColors.mantineColorTeal3,
  mantineDarkColorTealOutline: mantineColors.mantineColorTeal4,
  mantineDarkColorTealOutlineHover: "rgba(56, 217, 169, 0.05)",
  mantineDarkColorGreenText: mantineColors.mantineColorGreen4,
  mantineDarkColorGreenFilled: mantineColors.mantineColorGreen8,
  mantineDarkColorGreenFilledHover: mantineColors.mantineColorGreen9,
  mantineDarkColorGreenLight: "rgba(64, 192, 87, 0.15)",
  mantineDarkColorGreenLightHover: "rgba(64, 192, 87, 0.2)",
  mantineDarkColorGreenLightColor: mantineColors.mantineColorGreen3,
  mantineDarkColorGreenOutline: mantineColors.mantineColorGreen4,
  mantineDarkColorGreenOutlineHover: "rgba(105, 219, 124, 0.05)",
  mantineDarkColorLimeText: mantineColors.mantineColorLime4,
  mantineDarkColorLimeFilled: mantineColors.mantineColorLime8,
  mantineDarkColorLimeFilledHover: mantineColors.mantineColorLime9,
  mantineDarkColorLimeLight: "rgba(130, 201, 30, 0.15)",
  mantineDarkColorLimeLightHover: "rgba(130, 201, 30, 0.2)",
  mantineDarkColorLimeLightColor: mantineColors.mantineColorLime3,
  mantineDarkColorLimeOutline: mantineColors.mantineColorLime4,
  mantineDarkColorLimeOutlineHover: "rgba(169, 227, 75, 0.05)",
  mantineDarkColorYellowText: mantineColors.mantineColorYellow4,
  mantineDarkColorYellowFilled: mantineColors.mantineColorYellow8,
  mantineDarkColorYellowFilledHover: mantineColors.mantineColorYellow9,
  mantineDarkColorYellowLight: "rgba(250, 176, 5, 0.15)",
  mantineDarkColorYellowLightHover: "rgba(250, 176, 5, 0.2)",
  mantineDarkColorYellowLightColor: mantineColors.mantineColorYellow3,
  mantineDarkColorYellowOutline: mantineColors.mantineColorYellow4,
  mantineDarkColorYellowOutlineHover: "rgba(255, 212, 59, 0.05)",
  mantineDarkColorOrangeText: mantineColors.mantineColorOrange4,
  mantineDarkColorOrangeFilled: mantineColors.mantineColorOrange8,
  mantineDarkColorOrangeFilledHover: mantineColors.mantineColorOrange9,
  mantineDarkColorOrangeLight: "rgba(253, 126, 20, 0.15)",
  mantineDarkColorOrangeLightHover: "rgba(253, 126, 20, 0.2)",
  mantineDarkColorOrangeLightColor: mantineColors.mantineColorOrange3,
  mantineDarkColorOrangeOutline: mantineColors.mantineColorOrange4,
  mantineDarkColorOrangeOutlineHover: "rgba(255, 169, 77, 0.05)",
};

export default {
  darkMode: ["class", '[data-mantine-color-scheme="dark"]'],
  content: ["./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}"],
  theme: {
    screens: {
      xs: "576px",
      sm: "768px",
      md: "992px",
      lg: "1200px",
      xl: "1408px",
    },
    extend: {
      colors: {
        ...mantinePrimaryColors,
        ...mantineColors,
        ...mantineLightColor,
        ...mantineLightColorScheme,
        ...mantineLightColorScheme,
        ...mantineDarkColorScheme,
      },

      fontFamily: {
        ...mantineFontFamily,
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      fontSize: {
        ...mantineFontSize,
      },
      lineHeight: {
        ...mantineLineHeight,
      },
      spacing: {
        ...mantineSpacing,
      },
      borderRadius: {
        ...mantineBorderRadius,
      },
      boxShadow: {
        ...mantineBoxShadow,
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: true,
  },
} satisfies Config;
